In [1]:
from importlib import reload
import numpy as np
from matplotlib import pyplot as plt
import Single_qubit_design as sqd

In [2]:
reload(sqd)

<module 'Single_qubit_design' from 'D:\\Documents-cloud\\qubits\\simulation\\QCreator\\designs\\Single_qubit_design\\Single_qubit_design.py'>

# Draw a qubit design

In [3]:
g7,g8= sqd.draw_double_resonator(sqd.sample,sqd.elements,
                            sqd.coupler_start+2450, sqd.central_line_y, 150,
                             sqd.resonator_core,sqd.resonator_gap,15, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=2750,length_left1=100,length_right1=100,
                             closed_end_meander_length2=2850,length_left2=100,length_right2=100,
                             open_length1=1000,open_length2=1000,orientation='left')

In [4]:
g1,g2, par1, par2= sqd.draw_double_resonator_plus_double_qubit(sqd.sample,sqd.elements,
                            sqd.coupler_start, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3200,length_left1=350,length_right1=300,
                              closed_end_meander_length2=3300,length_left2=300,length_right2=350,
                             open_end_shift_length1=400, open_end_shift_length2=400,
                             qubit1=sqd.coaxmon1, coupler_name1='coupler2',
                             qubit2=sqd.coaxmon2, coupler_name2='coupler2',
                             orientation='left')

In [5]:
g3,g4, par1, par2= sqd.draw_double_resonator_plus_double_qubit(sqd.sample,sqd.elements,
                            sqd.coupler_start+1000, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3400,length_left1=350,length_right1=300,
                              closed_end_meander_length2=3500,length_left2=300,length_right2=350,
                             open_end_shift_length1=400, open_end_shift_length2=400,
                             qubit1=sqd.coaxmon3, coupler_name1='coupler2',
                             qubit2=sqd.coaxmon4, coupler_name2='coupler2',
                             orientation='left')

In [6]:
g5,g6, par1, par2= sqd.draw_double_resonator_plus_double_qubit(sqd.sample,sqd.elements,
                            sqd.coupler_start+1900, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3600,length_left1=350,length_right1=300,
                              closed_end_meander_length2=3700,length_left2=300,length_right2=350,
                             open_end_shift_length1=600, open_end_shift_length2=600,
                             qubit1=sqd.xmon2, coupler_name1='crab_up',
                             qubit2=sqd.xmon1, coupler_name2='crab_down',
                             orientation='left')

# Connect resonators into feedline

In [7]:
sqd.sample.connect_cpw(o1=sqd.p1, o2=g1, port1='port', port2='narrow', name='right TL', points=[])
sqd.sample.connect_cpw(o1=g2, o2=g3, port1='narrow', port2='narrow', name='right TL', points=[])
sqd.sample.connect_cpw(o1=g4, o2=g5, port1='narrow', port2='narrow', name='right TL', points=[])
sqd.sample.connect_cpw(o1=g6, o2=g7, port1='narrow', port2='narrow', name='right TL', points=[])
sqd.sample.connect_cpw(o1=g8, o2=sqd.p2, port1='narrow', port2='port', name='right TL', points=[])

CPW "right TL", l=68.000

In [8]:
# sqd.sample.connect_cpw(o1=sqd.p1, o2=g3, port1='port', port2='narrow', name='right TL', points=[])
# sqd.sample.connect_cpw(o1=g4, o2=sqd.p2, port1='narrow', port2='port', name='right TL', points=[])

In [8]:
sqd.sample.draw_design()
sqd.sample.watch()

C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\gdspy\path.py:827: UserWarning: [GDSPY] Possible inconsistency found in `FlexPath` due to sharp corner.
  warnings.warn(


# Connect contact pads

In [9]:
flux_pads_coaxmons = [
    (sqd.sample.qubits[0], sqd.pads_bottom[0], [((1015, 1077))]),
    (sqd.sample.qubits[1], sqd.pads_top[0], [(1047, 3620)]),
    (sqd.sample.qubits[2], sqd.pads_bottom[1], [(2000, 1077)]),
    (sqd.sample.qubits[3], sqd.pads_top[1], [(2036,3691)])]#[(2076, 3691)])]#[(2030, 3640)])]

flux_pads_xmons = [(sqd.sample.qubits[4], sqd.pads_top[2], [(3200, 3768)]),
                   (sqd.sample.qubits[5], sqd.pads_bottom[2], [(3200, 922)])]


for coaxmon, pad, points in flux_pads_coaxmons:  
    flux_line_narrowing_position = np.asarray(coaxmon.terminals['flux'].position)
    direction = [np.cos(coaxmon.terminals['flux'].orientation), 
                 np.sin(coaxmon.terminals['flux'].orientation)]
    narrowing_length = 25
    flux_line_narrowing_position = flux_line_narrowing_position - np.asarray(direction)*narrowing_length/2
    flux_line_narrowing = sqd.elements.Narrowing(name='flux_line_narrowing', position=flux_line_narrowing_position, 
                                             orientation=coaxmon.terminals['flux'].orientation+np.pi, 
                                             w1=coaxmon.terminals['flux'].w, 
                                             s1=coaxmon.terminals['flux'].s, g1=coaxmon.terminals['flux'].g,
                                             w2=sqd.tl_core, s2=sqd.tl_gap, g2=sqd.tl_ground, 
                                             layer_configuration=sqd.sample.layer_configuration, length=narrowing_length)
    sqd.sample.add(flux_line_narrowing)
    sqd.sample.connect(flux_line_narrowing, 'port1', coaxmon, 'flux')

    sqd.sample.connect_cpw(pad, flux_line_narrowing, 'port', 'port2', 'flux_control5', points=points)
    
for xmon, pad, points in flux_pads_xmons:  
    flux_line_narrowing_position = np.asarray(xmon.terminals['flux'].position)
    direction = [np.cos(xmon.terminals['flux'].orientation), 
                 np.sin(xmon.terminals['flux'].orientation)]
    narrowing_length = 20
    flux_line_narrowing_position = flux_line_narrowing_position - np.asarray(direction)*narrowing_length/2
    flux_line_narrowing = sqd.elements.Narrowing(name='flux_line_narrowing', position=flux_line_narrowing_position, 
                                             orientation=xmon.terminals['flux'].orientation+np.pi, 
                                             w1=xmon.terminals['flux'].w, 
                                             s1=xmon.terminals['flux'].s, g1=xmon.terminals['flux'].g,
                                             w2=sqd.tl_core, s2=sqd.tl_gap, g2=sqd.tl_ground, 
                                             layer_configuration=sqd.sample.layer_configuration, length=narrowing_length)
    sqd.sample.add(flux_line_narrowing)
    sqd.sample.connect(flux_line_narrowing, 'port1', xmon, 'flux')

    sqd.sample.connect_cpw(pad, flux_line_narrowing, 'port', 'port2', 'flux_control5', points=points)

In [11]:
sqd.sample.write_to_gds()

Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds


# Simulations

In [10]:
sqd.sample.draw_cap()

In [11]:
for i,qubit in enumerate(sqd.sample.qubits):
    caps=sqd.sample.calculate_qubit_capacitance(cell= sqd.sample.qubit_cap_cells[i], qubit=sqd.sample.qubits[i],
                                       mesh_volume=4)

Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds
For 0 conductor total length is:  33887
For 1 conductor total length is:  12258
For 2 conductor total length is:  2117
Sum : 48262
Data has been written into the file: D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\mesh_4k_data
Time for fastcap job is:  17.320002555847168
Capacitance results have been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\mesh_4k_results
Capacitance value in:  nanofarads
[<map object at 0x0000024EFB35DD00>, <map object at 0x0000024EFB35DBE0>, <map object at 0x0000024EFB35DA00>]
       0     1     2
0  151.2 -46.2 -15.4
1  -46.2  64.6  -4.8
2  -15.4  -4.8  25.0
Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds
For 0 conductor total length is:  33887
For 1 conductor total length is:  12258
For 2 conductor total l

In [12]:
sys, connections, elements_ = sqd.sample.get_tls()
f, delta, modes = sys.get_modes()

('down',)
('up',)


C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [21]:
connections

{(CPWCoupler "TL-resonator coupler", n=5, l=150.000, 'port1', 0): 1,
 (RectFanout closed end resonator fanout, n=5, grouping=(1, 4), 'wide', 0): 1,
 (CPWCoupler "TL-resonator coupler", n=5, l=150.000, 'port1', 1): 2,
 (RectFanout closed end resonator fanout, n=5, grouping=(1, 4), 'wide', 1): 2,
 (CPWCoupler "TL-resonator coupler", n=5, l=150.000, 'port1', 2): 3,
 (RectFanout closed end resonator fanout, n=5, grouping=(1, 4), 'wide', 2): 3,
 (CPWCoupler "TL-resonator coupler", n=5, l=150.000, 'port1', 3): 4,
 (RectFanout closed end resonator fanout, n=5, grouping=(1, 4), 'wide', 3): 4,
 (CPWCoupler "TL-resonator coupler", n=5, l=150.000, 'port1', 4): 5,
 (RectFanout closed end resonator fanout, n=5, grouping=(1, 4), 'wide', 4): 5,
 (RectFanout closed end resonator fanout, n=5, grouping=(1, 4),
  'center',
  0): 6,
 (RectGrounding cl1, 'wide', 0): 6,
 (RectFanout closed end resonator fanout, n=5, grouping=(1, 4),
  'center',
  1): 7,
 (RectGrounding cl1, 'wide', 1): 7,
 (RectFanout close

In [13]:
num_modes=18
(res_fr,kappa,_)=sqd.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

Resonance frequencies are, GHz/2pi: [4.5646054  4.56462902 4.92754409 4.92786994 4.92816427 4.92841241
 5.82298671 5.93784549 6.23048763 6.3594493  6.4989762  6.63882184
 7.39054578 7.5763216 ]
Kappas are, MHz/2pi: [0.00709107 0.00708637 0.00871181 0.00863901 0.00860897 0.00855075
 0.18132072 0.20679474 0.22132959 0.25493026 0.25516819 0.29312797
 0.02772073 0.03031085]
Quality factors are: [321856.09930166 322071.04342851 282808.23974009 285210.26556955
 286222.54557678 288185.93169526  16057.1461125   14356.85841491
  14075.1345606   12472.91987277  12734.691101    11324.10161642
 133303.59811409 124977.07176211]


In [13]:
num_modes=18
(res_fr,kappa,_)=sqd.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

Resonance frequencies are, GHz/2pi: [4.56460532 4.56462894 4.92754398 4.92786982 4.92816416 4.9284123
 5.82298671 5.93784549 6.23048763 6.3594493  6.4989762  6.63882183
 7.39054578 7.5763216 ]
Kappas are, MHz/2pi: [3.44802262e-05 2.93657851e-05 5.24749212e-04 4.45742130e-04
 4.09203406e-04 3.46428603e-04 1.81316763e-01 2.06791146e-01
 2.21274493e-01 2.54880858e-01 2.55123590e-01 2.93087135e-01
 2.77207285e-02 3.03108445e-02]
Quality factors are: [6.61916382e+07 7.77201923e+07 4.69514185e+06 5.52771378e+06
 6.02165584e+06 7.11317175e+06 1.60574968e+04 1.43571077e+04
 1.40786395e+04 1.24753372e+04 1.27369174e+04 1.13256794e+04
 1.33303600e+05 1.24977079e+05]


In [14]:
num_modes=18
f[:num_modes]/(2*np.pi)/1e9, delta[:num_modes]/1e6,f[:num_modes]/delta[:num_modes]/2 

(array([ 4.5646054 ,  4.56462902,  4.92754409,  4.92786994,  4.92816427,
         4.92841241,  5.82298671,  5.93784549,  6.23048763,  6.3594493 ,
         6.4989762 ,  6.63882184,  7.39054578,  7.5763216 , 17.44812088,
        17.79435768, 18.65625426, 19.04533686]),
 array([ 0.04455448,  0.04452497,  0.05473793,  0.05428051,  0.05409177,
         0.05372595,  1.13927171,  1.29932965,  1.39065485,  1.60177403,
         1.60326903,  1.84177735,  0.17417448,  0.19044866, 12.88652894,
        10.63503671, 15.04604638, 12.57226923]),
 array([321856.09930166, 322071.04342851, 282808.23974009, 285210.26556955,
        286222.54557678, 288185.93169526,  16057.1461125 ,  14356.85841491,
         14075.1345606 ,  12472.91987277,  12734.691101  ,  11324.10161642,
        133303.59811409, 124977.07176211,   4253.65811361,   5256.45795861,
          3895.39881928,   4759.10030713]))

In [14]:
num_modes=18
f[:num_modes]/(2*np.pi)/1e9, delta[:num_modes]/1e6,f[:num_modes]/delta[:num_modes]/2 

(array([ 4.56460532,  4.56462894,  4.92754398,  4.92786982,  4.92816416,
         4.9284123 ,  5.82298671,  5.93784549,  6.23048763,  6.3594493 ,
         6.4989762 ,  6.63882183,  7.39054578,  7.5763216 , 17.44812088,
        17.79435768, 18.65625426, 19.04533686]),
 array([2.16645651e-04, 1.84510670e-04, 3.29709654e-03, 2.80068040e-03,
        2.57110083e-03, 2.17667511e-03, 1.13924682e+00, 1.29930709e+00,
        1.39030864e+00, 1.60146366e+00, 1.60298879e+00, 1.84152078e+00,
        1.74174474e-01, 1.90448653e-01, 1.28865247e+01, 1.06350326e+01,
        1.50459927e+01, 1.25722149e+01]),
 array([6.61916382e+07, 7.77201923e+07, 4.69514185e+06, 5.52771378e+06,
        6.02165584e+06, 7.11317175e+06, 1.60574968e+04, 1.43571077e+04,
        1.40786395e+04, 1.24753372e+04, 1.27369174e+04, 1.13256794e+04,
        1.33303600e+05, 1.24977079e+05, 4.25365950e+03, 5.25645998e+03,
        3.89541273e+03, 4.75912088e+03]))

# Get s21 parameters

In [ ]:
f_ = np.linspace(6.9e9, 7.1e9, 2001)
# s11 = sample.get_s21('p1', 'p1', f_)
s11 = sample.get_s21('pad-left-0', 'pad-right-0', f_)

In [ ]:
import resonator_tools
from resonator_tools.circuit import notch_port, reflection_port

In [ ]:
fitter = notch_port(f_data=f_, z_data_raw=s11)
fitter.autofit()

In [ ]:
fitter.plotall()

In [ ]:
fitter.fitresults

# Estimate qubit-resonator parameters

In [9]:
rfr_ind=2
qfr_ind=0

In [10]:
sqd.get_grounded_qubit_resonator_coupling(par1,sqd.coaxmon1,'coupler2',res_fr[rfr_ind],res_fr[qfr_ind])

{'g': (97.56920699063008, 'MHz/2pi')}

In [11]:
sqd.get_grounded_qubit_resonator_parameters(par1,sqd.coaxmon1,'coupler2',res_fr[rfr_ind],res_fr[qfr_ind],kappa[rfr_ind])

Qubit- resonator detuning: -0.49145585956066373


{'g': (97.56920699063008, 'MHz/2pi'),
 'alpha': (-279.1099326319758, 'MHz/2pi'),
 'chi': (-7.016274947557198, 'MHz/2pi'),
 'T': (16.46560784708201, 'us'),
 'protection ratio': 25.371344627775542}

In [12]:
print("From AWR protection ratio is:", kappa[rfr_ind]/kappa[qfr_ind])

From AWR protection ratio is: 28.397216442594896


# Tests

In [10]:
g5,g6,res= sqd.draw_single_resonator(sqd.sample,sqd.elements,
                            sqd.coupler_start+1500, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground,
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length=3000,length_left=400,length_right=400,
                             open_end_legth=800,
                             port_orientation='right', direction_orientation='up')