In [1]:
from importlib import reload
import numpy as np
from matplotlib import pyplot as plt
import Single_qubit_design as sqd
import QCreator.auxiliary_functions as auxfuncs
import QCreator.elements as elements

In [13]:
reload(sqd)

<module 'Single_qubit_design' from 'E:\\Github2.0\\QCreator\\designs\\Single_qubit_design\\Single_qubit_design.py'>

In [2]:
sqd.sample.add(sqd.coaxmon1)
sqd.sample.add(sqd.coaxmon2)
sqd.sample.add(sqd.coaxmon3)
sqd.sample.add(sqd.coaxmon4)
sqd.sample.add(sqd.xmon1)
sqd.sample.add(sqd.xmon2)
sqd.sample.draw_design()

In [3]:
airbridge = elements.AirBridgeGeometry(pad_width = 5,
                                       pad_length = 4,
                                       bridge_width = 4,
                                       bridge_length = 38,
                                       pad_distance = 32,
                                       layer_configuration = sqd.sample.layer_configuration)

# Draw a qubit design

In [4]:
g1,g2, par1, par2= auxfuncs.draw_double_resonator_plus_double_qubit(sqd.sample,
                            sqd.coupler_start, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3200,length_left1=300,length_right1=300,
                              closed_end_meander_length2=3300,length_left2=300,length_right2=300,
                             open_end_shift_length1=400, open_end_shift_length2=400,
                             object1=sqd.coaxmon1, port1='coupler2',
                             object2=sqd.coaxmon2, port2='coupler2',
                             airbridge=airbridge, 
                             min_bridge_spacing=150,
                             port_orientation='left',
                            meander_first_intend_orientation='right')

In [5]:
g3,g4, par3, par4= auxfuncs.draw_double_resonator_plus_double_qubit(sqd.sample,
                            sqd.coupler_start+1000, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3400,length_left1=300,length_right1=350,
                              closed_end_meander_length2=3500,length_left2=350,length_right2=300,
                             open_end_shift_length1=400, open_end_shift_length2=400,
                             object1=sqd.coaxmon3, port1='coupler2',
                             object2=sqd.coaxmon4, port2='coupler2',
                             airbridge=airbridge, 
                             min_bridge_spacing=150,
                             port_orientation='left')

In [6]:
g5,g6, par5, par6= auxfuncs.draw_double_resonator_plus_double_qubit(sqd.sample,
                            sqd.coupler_start+1900, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3600,length_left1=300,length_right1=350,
                              closed_end_meander_length2=3700,length_left2=350,length_right2=300,
                             open_end_shift_length1=600, open_end_shift_length2=600,
                             object1=sqd.xmon2, port1='crab_up',
                             object2=sqd.xmon1, port2='crab_down',
                             airbridge=airbridge, 
                             min_bridge_spacing=150,
                             port_orientation='left')

In [7]:
g7, g8, _1, _2 = auxfuncs.draw_double_resonator(sqd.sample, 
                            sqd.coupler_start+2450, sqd.central_line_y, 150,
                             sqd.resonator_core,sqd.resonator_gap,15, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=2750,length_left1=100,length_right1=100,
                             closed_end_meander_length2=2850,length_left2=100,length_right2=100,
                             open_end_length1=1000,open_end_length2=1000,port_orientation='left',
                             airbridge=airbridge, 
                             min_bridge_spacing=150)

# Connect resonators into feedline

In [8]:
sqd.sample.connect_cpw(o1=sqd.p1, o2=g1, port1='port', port2='narrow', name='right TL', points=[],
                       airbridge=airbridge, min_spacing=150)
sqd.sample.connect_cpw(o1=g2, o2=g3, port1='narrow', port2='narrow', name='right TL', points=[],
                       airbridge=airbridge, min_spacing=150)
sqd.sample.connect_cpw(o1=g4, o2=g5, port1='narrow', port2='narrow', name='right TL', points=[],
                       airbridge=airbridge, min_spacing=150)
sqd.sample.connect_cpw(o1=g6, o2=g7, port1='narrow', port2='narrow', name='right TL', points=[],
                       airbridge=airbridge, min_spacing=150)
sqd.sample.connect_cpw(o1=g8, o2=sqd.p2, port1='narrow', port2='port', name='right TL', points=[],
                       airbridge=airbridge, min_spacing=150)

[CPW "right TLs0", l=68.000]

In [21]:
# sqd.sample.connect_cpw(o1=sqd.p1, o2=g3, port1='port', port2='narrow', name='right TL', points=[])
# sqd.sample.connect_cpw(o1=g4, o2=sqd.p2, port1='narrow', port2='port', name='right TL', points=[])

In [9]:
sqd.sample.draw_design()
sqd.sample.watch()

E:\py38\lib\site-packages\gdspy\path.py:827: UserWarning: [GDSPY] Possible inconsistency found in `FlexPath` due to sharp corner.
  warnings.warn(


In [13]:
sqd.sample.draw_cap()
for i,qubit in enumerate(sqd.sample.qubits):
    caps=sqd.sample.calculate_qubit_capacitance(cell= sqd.sample.qubit_cap_cells[i], qubit=sqd.sample.qubits[i],
                                       mesh_volume=10)

Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds
For 0 conductor total length is:  6561
For 1 conductor total length is:  1234
For 2 conductor total length is:  346
Sum : 8141
Data has been written into the file: D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\mesh_4k_data
Time for fastcap job is:  0.9063003063201904
Capacitance results have been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\mesh_4k_results
Capacitance value in:  nanofarads
[<map object at 0x0000024A2C463A30>, <map object at 0x0000024A2C463DC0>, <map object at 0x0000024A2C463BB0>]
      0     1     2
0  92.3 -21.7 -10.2
1 -21.7  29.8  -2.2
2 -10.2  -2.2  15.3
Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds
For 0 conductor total length is:  13734
For 1 conductor total length is:  4885
For 2 conductor total length is:

In [12]:
sys, connections, elements_ = sqd.sample.get_tls(cutoff=2e11)
f, delta, modes = sys.get_modes()
num_modes=18
(res_fr,kappa,_)=auxfuncs.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

('down',)
('up',)
Resonance frequencies are, GHz/2pi: [4.52133462 4.52175858 5.82822274 5.94357465 6.23383628 6.35672523
 6.52010911 6.64402013 6.67979049 7.37947516 7.56410607]
Kappas are, MHz/2pi: [2.21393495e-04 1.70610669e-04 1.81922358e-01 2.07585120e-01
 2.21566485e-01 2.56017966e-01 1.80223087e-01 2.77791362e-01
 1.00263883e-01 2.75055021e-02 3.00510795e-02]
Quality factors are: [1.02110828e+07 1.32516876e+07 1.60184345e+04 1.43159939e+04
 1.40676427e+04 1.24146077e+04 1.80889952e+04 1.19586514e+04
 3.33110503e+04 1.34145436e+05 1.25854149e+05]


In [13]:
f[:num_modes]/(2*np.pi)/1e9, delta[:num_modes]

(array([ 4.52133462,  4.52175858,  5.82822274,  5.94357465,  6.23383628,
         6.35672523,  6.52010911,  6.64402013,  6.67979049,  7.37947516,
         7.56410607, 16.25477751, 17.59409609, 17.95061229, 18.42787245,
        18.78509677, 19.11738899, 19.11910219]),
 array([1.39105635e+03, 1.07197845e+03, 1.14305189e+06, 1.30429578e+06,
        1.39214328e+06, 1.60860832e+06, 1.13237505e+06, 1.74541460e+06,
        6.29976555e+05, 1.72822167e+05, 1.88816501e+05, 9.38904851e+04,
        1.31224967e+07, 1.09455365e+07, 1.77137683e+11, 1.51464579e+07,
        4.88919709e+04, 7.48985780e+04]))

# Connect contact pads

In [10]:
flux_pads_coaxmons = [
    (sqd.sample.qubits[0], sqd.pads_bottom[0], [((1015, 1077))]),
    (sqd.sample.qubits[1], sqd.pads_top[0], [(1047, 3620)]),
    (sqd.sample.qubits[2], sqd.pads_bottom[1], [(2000, 1077)]),
    (sqd.sample.qubits[3], sqd.pads_top[1], [(2036,3691)])]#[(2076, 3691)])]#[(2030, 3640)])]

flux_pads_xmons = [(sqd.sample.qubits[4], sqd.pads_top[2], [(3200, 3768)]),
                   (sqd.sample.qubits[5], sqd.pads_bottom[2], [(3200, 922)])]


for coaxmon, pad, points in flux_pads_coaxmons:  
    flux_line_narrowing_position = np.asarray(coaxmon.terminals['flux'].position)
    direction = [np.cos(coaxmon.terminals['flux'].orientation), 
                 np.sin(coaxmon.terminals['flux'].orientation)]
    narrowing_length = 25
    flux_line_narrowing_position = flux_line_narrowing_position - np.asarray(direction)*narrowing_length/2
    flux_line_narrowing = sqd.elements.Narrowing(name='flux_line_narrowing', position=flux_line_narrowing_position, 
                                             orientation=coaxmon.terminals['flux'].orientation+np.pi, 
                                             w1=coaxmon.terminals['flux'].w, 
                                             s1=coaxmon.terminals['flux'].s, g1=coaxmon.terminals['flux'].g,
                                             w2=sqd.tl_core, s2=sqd.tl_gap, g2=sqd.tl_ground, 
                                             layer_configuration=sqd.sample.layer_configuration, length=narrowing_length)
    sqd.sample.add(flux_line_narrowing)
    sqd.sample.connect(flux_line_narrowing, 'port1', coaxmon, 'flux')
    sqd.sample.connect_cpw(pad, flux_line_narrowing, 'port', 'port2', 'flux_control5', points=points)
    
for xmon, pad, points in flux_pads_xmons:  
    flux_line_narrowing_position = np.asarray(xmon.terminals['flux'].position)
    direction = [np.cos(xmon.terminals['flux'].orientation), 
                 np.sin(xmon.terminals['flux'].orientation)]
    narrowing_length = 20
    flux_line_narrowing_position = flux_line_narrowing_position - np.asarray(direction)*narrowing_length/2
    flux_line_narrowing = sqd.elements.Narrowing(name='flux_line_narrowing', position=flux_line_narrowing_position, 
                                             orientation=xmon.terminals['flux'].orientation+np.pi, 
                                             w1=xmon.terminals['flux'].w, 
                                             s1=xmon.terminals['flux'].s, g1=xmon.terminals['flux'].g,
                                             w2=sqd.tl_core, s2=sqd.tl_gap, g2=sqd.tl_ground, 
                                             layer_configuration=sqd.sample.layer_configuration, length=narrowing_length)
    sqd.sample.add(flux_line_narrowing)
    sqd.sample.connect(flux_line_narrowing, 'port1', xmon, 'flux')

    sqd.sample.connect_cpw(pad, flux_line_narrowing, 'port', 'port2', 'flux_control5', points=points)

3.963428267055999
8.63937979737193
3.931110222065086
8.633698040331083


In [11]:
sqd.sample.draw_design()
sqd.sample.watch()

In [14]:
sys, connections, elements_ = sqd.sample.get_tls(cutoff=2e11)
f, delta, modes = sys.get_modes()
num_modes=18
(res_fr,kappa,_)=auxfuncs.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

('down',)
('up',)


C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


Resonance frequencies are, GHz/2pi: [4.52784195 4.52827347 5.83072316 5.94720311 6.23496276 6.36009521
 6.53090862 6.6477703  6.70053212 7.37947516 7.56410607]
Kappas are, MHz/2pi: [2.97360533e-04 2.45417032e-04 1.82191404e-01 2.07911377e-01
 2.21830204e-01 2.56249965e-01 2.00489137e-01 2.86867293e-01
 7.16024238e-02 2.75055897e-02 3.00511417e-02]
Quality factors are: [7613387.52425045 9225670.74272625   16001.64179267   14302.25514696
   14053.45765459   12409.94358619   16287.437577     11586.83903494
   46789.84150929  134145.0092395   125853.88831481]


In [15]:
f[:num_modes]/(2*np.pi)/1e9, delta[:num_modes]

(array([ 4.52784195,  4.52827347,  5.83072316,  5.94720311,  6.23496276,
         6.36009521,  6.53090862,  6.6477703 ,  6.70053212,  7.37947516,
         7.56410607, 16.27803393, 17.60224328, 17.96227995, 18.42793273,
        18.78854125, 19.21819921, 19.2477994 ]),
 array([1.86837133e+03, 1.54200069e+03, 1.14474235e+06, 1.30634571e+06,
        1.39380028e+06, 1.61006601e+06, 1.25971040e+06, 1.80244036e+06,
        4.49891297e+05, 1.72822717e+05, 1.88816892e+05, 1.70655985e+05,
        1.31429578e+07, 1.10148250e+07, 1.77138260e+11, 1.51310012e+07,
        1.29724001e+07, 6.09205099e+06]))

In [12]:
sqd.sample.write_to_gds()

Gds file has been writen here:  E:\Github2.0\QCreator\designs\Single_qubit_design\1Q_test.gds


# Simulations

In [17]:
sys, connections, elements_ = sqd.sample.get_tls(cutoff=2e11)
f, delta, modes = sys.get_modes()

('down',)
('up',)


C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [15]:
num_modes=18
(res_fr,kappa,_)=auxfuncs.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

('down',)
('up',)


C:\Users\di82dac\Anaconda3\envs\qcreator\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


Resonance frequencies are, GHz/2pi: [4.52133462 4.52175859 5.82822274 5.94357465 6.23383628 6.35672523
 6.52010911 6.64402013 6.6797905  7.37947516 7.56410607]
Kappas are, MHz/2pi: [2.93866718e-04 2.43155157e-04 1.81923200e-01 2.07586056e-01
 2.21566789e-01 2.56018345e-01 1.80268100e-01 2.77791952e-01
 1.00374634e-01 2.75055002e-02 3.00510816e-02]
Quality factors are: [7692832.07148414 9298093.10784708   16018.36037189   14315.92940673
   14067.62338358   12414.58934844   18084.47836791   11958.62601791
   33274.29567177  134145.44538219  125854.13991798]


In [18]:
num_modes=18
(res_fr,kappa,_)=sqd.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

Resonance frequencies are, GHz/2pi: [4.92754409 4.92786994 4.92816427 4.92841241 5.82237707 5.93725003
 6.23048763 6.3594493  6.4989762  6.63882184 7.39054578 7.5763216 ]
Kappas are, MHz/2pi: [0.00871181 0.00863901 0.00860897 0.00855075 0.18133009 0.20679175
 0.22132931 0.25493007 0.25516803 0.29312784 0.02772073 0.03031085]
Quality factors are: [282808.26117442 285210.266044   286222.54725799 288185.93872864
  16054.63594337  14355.6261769   14075.15255892  12472.92879454
  12734.69930794  11324.10647405 133303.58801683 124977.06592616]


# Get s21 parameters

In [ ]:
f_ = np.linspace(6.9e9, 7.1e9, 2001)
# s11 = sample.get_s21('p1', 'p1', f_)
s11 = sample.get_s21('pad-left-0', 'pad-right-0', f_)

In [ ]:
import resonator_tools
from resonator_tools.circuit import notch_port, reflection_port

In [ ]:
fitter = notch_port(f_data=f_, z_data_raw=s11)
fitter.autofit()

In [ ]:
fitter.plotall()

In [ ]:
fitter.fitresults

# Estimate qubit-resonator parameters

In [9]:
rfr_ind=2
qfr_ind=0

In [10]:
auxfuncs.get_grounded_qubit_resonator_coupling(par1,sqd.coaxmon1,'coupler2',res_fr[rfr_ind],res_fr[qfr_ind])

{'g': (97.56920699063008, 'MHz/2pi')}

In [11]:
auxfuncs.get_grounded_qubit_resonator_parameters(par1,sqd.coaxmon1,'coupler2',res_fr[rfr_ind],res_fr[qfr_ind],kappa[rfr_ind])

Qubit- resonator detuning: -0.49145585956066373


{'g': (97.56920699063008, 'MHz/2pi'),
 'alpha': (-279.1099326319758, 'MHz/2pi'),
 'chi': (-7.016274947557198, 'MHz/2pi'),
 'T': (16.46560784708201, 'us'),
 'protection ratio': 25.371344627775542}

In [12]:
print("From AWR protection ratio is:", kappa[rfr_ind]/kappa[qfr_ind])

From AWR protection ratio is: 28.397216442594896


# Tests

In [10]:
g5,g6,res= sqd.draw_single_resonator(sqd.sample,sqd.elements,
                            sqd.coupler_start+1500, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground,
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length=3000,length_left=400,length_right=400,
                             open_end_legth=800,
                             port_orientation='right', direction_orientation='up')