In [1]:
from importlib import reload
import numpy as np
from matplotlib import pyplot as plt
import Single_qubit_design as sqd

In [2]:
reload(sqd)

<module 'Single_qubit_design' from 'D:\\Documents-cloud\\qubits\\simulation\\QCreator\\designs\\Single_qubit_design\\Single_qubit_design.py'>

# Draw a qubit design

In [3]:
g7,g8= sqd.draw_double_resonator(sqd.sample,sqd.elements,
                            sqd.coupler_start+2450, sqd.central_line_y, 150,
                             sqd.resonator_core,sqd.resonator_gap,15, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=2750,length_left1=100,length_right1=100,
                             closed_end_meander_length2=2850,length_left2=100,length_right2=100,
                             open_length1=1000,open_length2=1000,orientation='left')

In [4]:
g1,g2, par1, par2= sqd.draw_double_resonator_plus_double_qubit(sqd.sample,sqd.elements,
                            sqd.coupler_start, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3200,length_left1=350,length_right1=300,
                              closed_end_meander_length2=3300,length_left2=300,length_right2=350,
                             open_end_shift_length1=400, open_end_shift_length2=400,
                             qubit1=sqd.coaxmon1, coupler_name1='coupler2',
                             qubit2=sqd.coaxmon2, coupler_name2='coupler2',
                             orientation='left')

In [5]:
g3,g4, par1, par2= sqd.draw_double_resonator_plus_double_qubit(sqd.sample,sqd.elements,
                            sqd.coupler_start+1000, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3400,length_left1=350,length_right1=300,
                              closed_end_meander_length2=3500,length_left2=300,length_right2=350,
                             open_end_shift_length1=400, open_end_shift_length2=400,
                             qubit1=sqd.coaxmon3, coupler_name1='coupler2',
                             qubit2=sqd.coaxmon4, coupler_name2='coupler2',
                             orientation='left')

In [6]:
g5,g6, par1, par2= sqd.draw_double_resonator_plus_double_qubit(sqd.sample,sqd.elements,
                            sqd.coupler_start+1900, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground, 
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length1=3600,length_left1=350,length_right1=300,
                              closed_end_meander_length2=3700,length_left2=300,length_right2=350,
                             open_end_shift_length1=600, open_end_shift_length2=600,
                             qubit1=sqd.xmon2, coupler_name1='crab_up',
                             qubit2=sqd.xmon1, coupler_name2='crab_down',
                             orientation='left')

# Connect resonators into feedline

In [7]:
sqd.sample.connect_cpw(o1=sqd.p1, o2=g1, port1='port', port2='narrow', name='right TL', points=[])
sqd.sample.connect_cpw(o1=g2, o2=g3, port1='narrow', port2='narrow', name='right TL', points=[])
sqd.sample.connect_cpw(o1=g4, o2=g5, port1='narrow', port2='narrow', name='right TL', points=[])
sqd.sample.connect_cpw(o1=g6, o2=g7, port1='narrow', port2='narrow', name='right TL', points=[])
sqd.sample.connect_cpw(o1=g8, o2=sqd.p2, port1='narrow', port2='port', name='right TL', points=[])

CPW "right TL", l=68.000

In [8]:
# sqd.sample.connect_cpw(o1=sqd.p1, o2=g3, port1='port', port2='narrow', name='right TL', points=[])
# sqd.sample.connect_cpw(o1=g4, o2=sqd.p2, port1='narrow', port2='port', name='right TL', points=[])

In [9]:
sqd.sample.draw_design()
sqd.sample.watch()

C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\gdspy\path.py:827: UserWarning: [GDSPY] Possible inconsistency found in `FlexPath` due to sharp corner.
  warnings.warn(


In [10]:
sqd.sample.draw_cap()
for i,qubit in enumerate(sqd.sample.qubits):
    caps=sqd.sample.calculate_qubit_capacitance(cell= sqd.sample.qubit_cap_cells[i], qubit=sqd.sample.qubits[i],
                                       mesh_volume=4)

Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds
For 0 conductor total length is:  33887
For 1 conductor total length is:  12258
For 2 conductor total length is:  2117
Sum : 48262
Data has been written into the file: D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\mesh_4k_data
Time for fastcap job is:  6.72308611869812
Capacitance results have been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\mesh_4k_results
Capacitance value in:  nanofarads
[<map object at 0x0000029761CE76D0>, <map object at 0x0000029761CE7970>, <map object at 0x0000029761CE7A30>]
       0     1     2
0  151.2 -46.2 -15.4
1  -46.2  64.6  -4.8
2  -15.4  -4.8  25.0
Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds
For 0 conductor total length is:  33887
For 1 conductor total length is:  12258
For 2 conductor total len

In [11]:
sys, connections, elements_ = sqd.sample.get_tls(cutoff=2e11)
f, delta, modes = sys.get_modes()
num_modes=18
(res_fr,kappa,_)=sqd.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

('down',)
('up',)
Resonance frequencies are, GHz/2pi: [4.52007265 4.52022559 4.52036958 4.52049582 5.82822275 5.94357466
 6.23383494 6.36343171 6.50355906 6.64409482 7.37947516 7.56410607]
Kappas are, MHz/2pi: [2.27138911e-04 1.94496710e-04 1.92519560e-04 1.62932994e-04
 1.81919142e-01 2.07579710e-01 2.22030489e-01 2.55763623e-01
 2.55957034e-01 2.94123916e-01 2.75044666e-02 3.00502815e-02]
Quality factors are: [9.95001830e+06 1.16203138e+07 1.17400268e+07 1.38722542e+07
 1.60187176e+04 1.43163671e+04 1.40382408e+04 1.24400641e+04
 1.27043960e+04 1.12947205e+04 1.34150487e+05 1.25857491e+05]


In [12]:
f[:num_modes]/(2*np.pi)/1e9, delta[:num_modes]

(array([ 4.52007265,  4.52022559,  4.52036958,  4.52049582,  5.82822275,
         5.94357466,  6.23383494,  6.36343171,  6.50355906,  6.64409482,
         7.37947516,  7.56410607, 17.59417693, 17.95076339, 18.42786821,
        18.78501022, 19.15266763, 19.1543113 ]),
 array([1.42715587e+03, 1.22205887e+03, 1.20963607e+03, 1.02373819e+03,
        1.14303168e+06, 1.30426179e+06, 1.39505871e+06, 1.60701024e+06,
        1.60822548e+06, 1.84803506e+06, 1.72815660e+05, 1.88811487e+05,
        1.31249004e+07, 1.09497061e+07, 1.77137720e+11, 1.52401861e+07,
        4.60737621e+04, 6.92349338e+04]))

# Connect contact pads

In [13]:
flux_pads_coaxmons = [
    (sqd.sample.qubits[0], sqd.pads_bottom[0], [((1015, 1077))]),
    (sqd.sample.qubits[1], sqd.pads_top[0], [(1047, 3620)]),
    (sqd.sample.qubits[2], sqd.pads_bottom[1], [(2000, 1077)]),
    (sqd.sample.qubits[3], sqd.pads_top[1], [(2036,3691)])]#[(2076, 3691)])]#[(2030, 3640)])]

flux_pads_xmons = [(sqd.sample.qubits[4], sqd.pads_top[2], [(3200, 3768)]),
                   (sqd.sample.qubits[5], sqd.pads_bottom[2], [(3200, 922)])]


for coaxmon, pad, points in flux_pads_coaxmons:  
    flux_line_narrowing_position = np.asarray(coaxmon.terminals['flux'].position)
    direction = [np.cos(coaxmon.terminals['flux'].orientation), 
                 np.sin(coaxmon.terminals['flux'].orientation)]
    narrowing_length = 25
    flux_line_narrowing_position = flux_line_narrowing_position - np.asarray(direction)*narrowing_length/2
    flux_line_narrowing = sqd.elements.Narrowing(name='flux_line_narrowing', position=flux_line_narrowing_position, 
                                             orientation=coaxmon.terminals['flux'].orientation+np.pi, 
                                             w1=coaxmon.terminals['flux'].w, 
                                             s1=coaxmon.terminals['flux'].s, g1=coaxmon.terminals['flux'].g,
                                             w2=sqd.tl_core, s2=sqd.tl_gap, g2=sqd.tl_ground, 
                                             layer_configuration=sqd.sample.layer_configuration, length=narrowing_length)
    sqd.sample.add(flux_line_narrowing)
    sqd.sample.connect(flux_line_narrowing, 'port1', coaxmon, 'flux')

    sqd.sample.connect_cpw(pad, flux_line_narrowing, 'port', 'port2', 'flux_control5', points=points)
    
for xmon, pad, points in flux_pads_xmons:  
    flux_line_narrowing_position = np.asarray(xmon.terminals['flux'].position)
    direction = [np.cos(xmon.terminals['flux'].orientation), 
                 np.sin(xmon.terminals['flux'].orientation)]
    narrowing_length = 20
    flux_line_narrowing_position = flux_line_narrowing_position - np.asarray(direction)*narrowing_length/2
    flux_line_narrowing = sqd.elements.Narrowing(name='flux_line_narrowing', position=flux_line_narrowing_position, 
                                             orientation=xmon.terminals['flux'].orientation+np.pi, 
                                             w1=xmon.terminals['flux'].w, 
                                             s1=xmon.terminals['flux'].s, g1=xmon.terminals['flux'].g,
                                             w2=sqd.tl_core, s2=sqd.tl_gap, g2=sqd.tl_ground, 
                                             layer_configuration=sqd.sample.layer_configuration, length=narrowing_length)
    sqd.sample.add(flux_line_narrowing)
    sqd.sample.connect(flux_line_narrowing, 'port1', xmon, 'flux')

    sqd.sample.connect_cpw(pad, flux_line_narrowing, 'port', 'port2', 'flux_control5', points=points)

In [14]:
sys, connections, elements_ = sqd.sample.get_tls(cutoff=2e11)
f, delta, modes = sys.get_modes()
num_modes=18
(res_fr,kappa,_)=sqd.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

('down',)
('up',)


C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


Resonance frequencies are, GHz/2pi: [4.52007276 4.5202257  4.52036969 4.52049593 5.82822275 5.94357466
 6.23383494 6.36343171 6.50355906 6.64409482 7.37947516 7.56410607]
Kappas are, MHz/2pi: [0.00888337 0.00885354 0.00885518 0.00882802 0.18191998 0.20758065
 0.22206676 0.25579755 0.25598888 0.29415406 0.02750447 0.03005028]
Quality factors are: [254411.98003081 255277.79215207 255238.66642629 256031.02119629
  16018.6436483   14316.30242229  14035.94819731  12438.41418862
  12702.81536347  11293.56316752 134150.48738866 125857.48934048]


In [15]:
f[:num_modes]/(2*np.pi)/1e9, delta[:num_modes]

(array([ 4.52007276,  4.5202257 ,  4.52036969,  4.52049593,  5.82822275,
         5.94357466,  6.23383494,  6.36343171,  6.50355906,  6.64409482,
         7.37947516,  7.56410607, 17.59417702, 17.95076356, 18.42786821,
        18.78501022, 19.15271223, 19.1543558 ]),
 array([5.58158754e+04, 5.56284498e+04, 5.56387494e+04, 5.54681098e+04,
        1.14303696e+06, 1.30426768e+06, 1.39528657e+06, 1.60722340e+06,
        1.60842560e+06, 1.84822444e+06, 1.72815659e+05, 1.88811490e+05,
        1.31395413e+07, 1.09763245e+07, 1.77137720e+11, 1.52402440e+07,
        6.03131000e+06, 6.04288723e+06]))

In [16]:
sqd.sample.write_to_gds()

Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds


# Simulations

In [17]:
sys, connections, elements_ = sqd.sample.get_tls()
f, delta, modes = sys.get_modes()

('down',)
('up',)


C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [18]:
num_modes=18
(res_fr,kappa,_)=sqd.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

Resonance frequencies are, GHz/2pi: [4.92754409 4.92786994 4.92816427 4.92841241 5.82237707 5.93725003
 6.23048763 6.3594493  6.4989762  6.63882184 7.39054578 7.5763216 ]
Kappas are, MHz/2pi: [0.00871181 0.00863901 0.00860897 0.00855075 0.18133009 0.20679175
 0.22132931 0.25493007 0.25516803 0.29312784 0.02772073 0.03031085]
Quality factors are: [282808.26117442 285210.266044   286222.54725799 288185.93872864
  16054.63594337  14355.6261769   14075.15255892  12472.92879454
  12734.69930794  11324.10647405 133303.58801683 124977.06592616]


# Get s21 parameters

In [ ]:
f_ = np.linspace(6.9e9, 7.1e9, 2001)
# s11 = sample.get_s21('p1', 'p1', f_)
s11 = sample.get_s21('pad-left-0', 'pad-right-0', f_)

In [ ]:
import resonator_tools
from resonator_tools.circuit import notch_port, reflection_port

In [ ]:
fitter = notch_port(f_data=f_, z_data_raw=s11)
fitter.autofit()

In [ ]:
fitter.plotall()

In [ ]:
fitter.fitresults

# Estimate qubit-resonator parameters

In [9]:
rfr_ind=2
qfr_ind=0

In [10]:
sqd.get_grounded_qubit_resonator_coupling(par1,sqd.coaxmon1,'coupler2',res_fr[rfr_ind],res_fr[qfr_ind])

{'g': (97.56920699063008, 'MHz/2pi')}

In [11]:
sqd.get_grounded_qubit_resonator_parameters(par1,sqd.coaxmon1,'coupler2',res_fr[rfr_ind],res_fr[qfr_ind],kappa[rfr_ind])

Qubit- resonator detuning: -0.49145585956066373


{'g': (97.56920699063008, 'MHz/2pi'),
 'alpha': (-279.1099326319758, 'MHz/2pi'),
 'chi': (-7.016274947557198, 'MHz/2pi'),
 'T': (16.46560784708201, 'us'),
 'protection ratio': 25.371344627775542}

In [12]:
print("From AWR protection ratio is:", kappa[rfr_ind]/kappa[qfr_ind])

From AWR protection ratio is: 28.397216442594896


# Tests

In [10]:
g5,g6,res= sqd.draw_single_resonator(sqd.sample,sqd.elements,
                            sqd.coupler_start+1500, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground,
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length=3000,length_left=400,length_right=400,
                             open_end_legth=800,
                             port_orientation='right', direction_orientation='up')