This calculation is based on the paper used in the website:
https://smm.misis.ru/CPW-resonator-coupling/

In [1]:
from сonformal_mapping import *
import numpy as np
import pandas as pd

an **epsilon value** of an used dielectric wafer can be changed inside the сonformal_mapping library

the **default value is 11.45**

# Used structure

picture is taken from the website specified above

![alt text](example.png "Title")

write down the widths of lines and spaces sequentially: AB,BC...

In [2]:
result=ConformalMapping([4,7,4,6,4,7,4])
feedline=0
resonator=2

In [3]:
C, L,Z = result.cl_and_Ll()
reduced_table_C=np.asarray([[C[feedline,feedline],C[feedline,resonator]],
                            [C[resonator,feedline],C[resonator,resonator]]])
reduced_table_L=np.asarray([[L[feedline,feedline],L[feedline,resonator]],
                            [L[resonator,feedline],L[resonator,resonator]]])
cap, ind=pd.DataFrame(reduced_table_C*1e12),pd.DataFrame(reduced_table_L*1e9)

In [4]:
Z

array([[66.92711636, 61.69188694, 47.47323038],
       [61.69188694, 80.60811746, 61.69188694],
       [47.47323038, 61.69188694, 66.92711636]])

In [5]:
cap

0           1
0  165.604763  -10.808861
1  -10.808861  165.604763

In [6]:
ind

0           1
0  500.619333  108.005291
1  108.005291  500.619333

In [12]:
coupling_matrix = np.sqrt(reduced_table_L@np.linalg.inv(reduced_table_C))

In [14]:
np.sqrt(L@np.linalg.inv(C))

array([[66.92711636, 61.69188694, 47.47323038],
       [61.69188694, 80.60811746, 61.69188694],
       [47.47323038, 61.69188694, 66.92711636]])

In [13]:
coupling_matrix

array([[55.48566933, 29.20835839],
       [29.20835839, 55.48566933]])