In [1]:
from importlib import reload
import numpy as np
from matplotlib import pyplot as plt
import Single_qubit_design_PP_qubits as sqd
import QCreator.auxiliary_functions as auxfuncs

In [2]:
reload(sqd)

<module 'Single_qubit_design_PP_qubits' from 'E:\\Github2.0\\QCreator\\designs\\Single_qubit_design_pp_qubits\\Single_qubit_design_PP_qubits.py'>

In [3]:
sqd.sample.draw_design(True)
sqd.sample.draw_terminals()
sqd.sample.watch(True)

# Draw a qubit design

In [4]:
coupler_start_x,coupler_start_y = (2000,3000)
grounding_width=10
coupler_length=400

In [5]:
res_coupler_q1,res_q1_params = auxfuncs.draw_rounded_single_resonator_plus_qubit(sqd.sample,
                          coupler_start_x, coupler_start_y, coupler_length,
                          sqd.resonator_core,sqd.resonator_gap, sqd.resonator_ground,
                          sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width,
                          closed_end_meander_length=2000, length_left=300, length_right=300,
                          min_bridge_spacing = None,
                          airbridge = None, object1=sqd.sample.qubits[0], port='coupler0',
                          open_end_length = 1000,
                          port_orientation='left', direction_orientation='up')

In [6]:
res_coupler_q2,res_q2_params = auxfuncs.draw_rounded_single_resonator_plus_qubit(sqd.sample,
                          coupler_start_x+5000, coupler_start_y, coupler_length,
                          sqd.resonator_core,sqd.resonator_gap, sqd.resonator_ground,
                          sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width,
                          closed_end_meander_length=2000, length_left=300, length_right=300,
                          min_bridge_spacing = None,
                          airbridge = None, object1=sqd.sample.qubits[1], port='coupler0',
                          open_end_length = 1000,
                          port_orientation='right', direction_orientation='up')

# Connect resonators into feedline

In [9]:
sqd.sample.connect_cpw(o1=sqd.p1, o2=res_coupler_q1, port1='port', port2='port2', name='feedline', 
                       points=[])
sqd.sample.connect_cpw(o1=res_coupler_q1, o2=res_coupler_q2, port1='port1', port2='port2', name='feedline', 
                       points=[])

[CPW "feedline", l=4600.000]

In [10]:
sqd.sample.draw_design(True)
sqd.sample.draw_terminals()
sqd.sample.watch(True)

In [11]:
# grid_ground = sqd.elements.GridGround(sqd.sample.chip_geometry, sqd.sample.layer_configuration, sqd.sample.objects, 
#                                   width=4, period=25)
# sqd.sample.add(grid_ground)

In [12]:
sqd.sample.write_to_gds()

Gds file has been writen here:  C:\Python\Github\QCreator\designs\Single_qubit_design_pp_qubits/1Q_test.gds


In [10]:
# sqd.sample.draw_cap()
# for i,qubit in enumerate(sqd.sample.qubits):
#     caps=sqd.sample.calculate_qubit_capacitance(cell= sqd.sample.qubit_cap_cells[i], qubit=sqd.sample.qubits[i],
#                                        mesh_volume=10)

Gds file has been writen here:  C:\Python\Github\QCreator\designs\Single_qubit_design\1Q_test.gds
For 0 conductor total length is:  16023
For 1 conductor total length is:  3024
For 2 conductor total length is:  846
Sum : 19893
Data has been written into the file: C:\Python\Github\QCreator\designs\Single_qubit_design\mesh_4k_data
Time for fastcap job is:  1.7464215755462646
Capacitance results have been writen here:  C:\Python\Github\QCreator\designs\Single_qubit_design\mesh_4k_results
Capacitance value in:  nanofarads
[<map object at 0x00000296556DDDF0>, <map object at 0x00000296556DD340>, <map object at 0x00000296556DD310>]
      0     1     2
0  92.6 -21.9 -10.3
1 -21.9  30.0  -2.3
2 -10.3  -2.3  15.5
Gds file has been writen here:  C:\Python\Github\QCreator\designs\Single_qubit_design\1Q_test.gds
For 0 conductor total length is:  33887
For 1 conductor total length is:  12258
For 2 conductor total length is:  2117
Sum : 48262
Data has been written into the file: C:\Python\Github\QCre

In [12]:
sys, connections, elements_ = sqd.sample.get_tls(cutoff=2e11)
f, delta, modes = sys.get_modes()
num_modes=18
(res_fr,kappa,_)=auxfuncs.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

('down',)
('up',)
Resonance frequencies are, GHz/2pi: [4.52133462 4.52175858 5.82822274 5.94357465 6.23383628 6.35672523
 6.52010911 6.64402013 6.67979049 7.37947516 7.56410607]
Kappas are, MHz/2pi: [2.21393495e-04 1.70610669e-04 1.81922358e-01 2.07585120e-01
 2.21566485e-01 2.56017966e-01 1.80223087e-01 2.77791362e-01
 1.00263883e-01 2.75055021e-02 3.00510795e-02]
Quality factors are: [1.02110828e+07 1.32516876e+07 1.60184345e+04 1.43159939e+04
 1.40676427e+04 1.24146077e+04 1.80889952e+04 1.19586514e+04
 3.33110503e+04 1.34145436e+05 1.25854149e+05]


In [13]:
f[:num_modes]/(2*np.pi)/1e9, delta[:num_modes]

(array([ 4.52133462,  4.52175858,  5.82822274,  5.94357465,  6.23383628,
         6.35672523,  6.52010911,  6.64402013,  6.67979049,  7.37947516,
         7.56410607, 16.25477751, 17.59409609, 17.95061229, 18.42787245,
        18.78509677, 19.11738899, 19.11910219]),
 array([1.39105635e+03, 1.07197845e+03, 1.14305189e+06, 1.30429578e+06,
        1.39214328e+06, 1.60860832e+06, 1.13237505e+06, 1.74541460e+06,
        6.29976555e+05, 1.72822167e+05, 1.88816501e+05, 9.38904851e+04,
        1.31224967e+07, 1.09455365e+07, 1.77137683e+11, 1.51464579e+07,
        4.88919709e+04, 7.48985780e+04]))

# Connect contact pads

In [14]:
flux_pads_coaxmons = [
    (sqd.sample.qubits[0], sqd.pads_bottom[0], [((1015, 1077))]),
    (sqd.sample.qubits[1], sqd.pads_top[0], [(1047, 3620)]),
    (sqd.sample.qubits[2], sqd.pads_bottom[1], [(2000, 1077)]),
    (sqd.sample.qubits[3], sqd.pads_top[1], [(2036,3691)])]#[(2076, 3691)])]#[(2030, 3640)])]

flux_pads_xmons = [(sqd.sample.qubits[4], sqd.pads_top[2], [(3200, 3768)]),
                   (sqd.sample.qubits[5], sqd.pads_bottom[2], [(3200, 922)])]


for coaxmon, pad, points in flux_pads_coaxmons:  
    flux_line_narrowing_position = np.asarray(coaxmon.terminals['flux'].position)
    direction = [np.cos(coaxmon.terminals['flux'].orientation), 
                 np.sin(coaxmon.terminals['flux'].orientation)]
    narrowing_length = 25
    flux_line_narrowing_position = flux_line_narrowing_position - np.asarray(direction)*narrowing_length/2
    flux_line_narrowing = sqd.elements.Narrowing(name='flux_line_narrowing', position=flux_line_narrowing_position, 
                                             orientation=coaxmon.terminals['flux'].orientation+np.pi, 
                                             w1=coaxmon.terminals['flux'].w, 
                                             s1=coaxmon.terminals['flux'].s, g1=coaxmon.terminals['flux'].g,
                                             w2=sqd.tl_core, s2=sqd.tl_gap, g2=sqd.tl_ground, 
                                             layer_configuration=sqd.sample.layer_configuration, length=narrowing_length)
    sqd.sample.add(flux_line_narrowing)
    sqd.sample.connect(flux_line_narrowing, 'port1', coaxmon, 'flux')

    sqd.sample.connect_cpw(pad, flux_line_narrowing, 'port', 'port2', 'flux_control5', points=points)
    
for xmon, pad, points in flux_pads_xmons:  
    flux_line_narrowing_position = np.asarray(xmon.terminals['flux'].position)
    direction = [np.cos(xmon.terminals['flux'].orientation), 
                 np.sin(xmon.terminals['flux'].orientation)]
    narrowing_length = 20
    flux_line_narrowing_position = flux_line_narrowing_position - np.asarray(direction)*narrowing_length/2
    flux_line_narrowing = sqd.elements.Narrowing(name='flux_line_narrowing', position=flux_line_narrowing_position, 
                                             orientation=xmon.terminals['flux'].orientation+np.pi, 
                                             w1=xmon.terminals['flux'].w, 
                                             s1=xmon.terminals['flux'].s, g1=xmon.terminals['flux'].g,
                                             w2=sqd.tl_core, s2=sqd.tl_gap, g2=sqd.tl_ground, 
                                             layer_configuration=sqd.sample.layer_configuration, length=narrowing_length)
    sqd.sample.add(flux_line_narrowing)
    sqd.sample.connect(flux_line_narrowing, 'port1', xmon, 'flux')

    sqd.sample.connect_cpw(pad, flux_line_narrowing, 'port', 'port2', 'flux_control5', points=points)

cpw segments [{'type': 'endpoint', 'endpoint': array([1175.,  800.])}, {'type': 'segment', 'endpoint': array([1175.        ,  810.85009967]), 'startpoint': array([1175.,  800.])}, {'type': 'turn', 'turn': 0.6174578771327504}, {'type': 'segment', 'endpoint': array([1080.50840693,  984.74479842]), 'startpoint': array([1151.,  884.])}, {'type': 'turn', 'turn': -1.4477705171092345}, {'type': 'segment', 'endpoint': array([1265.54003408, 1305.98779803]), 'startpoint': array([1099., 1153.])}, {'type': 'turn', 'turn': 0.081351926647796}, {'type': 'endpoint', 'endpoint': array([1274.71845581, 1315.23897193]), 'startpoint': array([1272., 1313.])}]
cpw segments [{'type': 'endpoint', 'endpoint': array([1175., 3900.])}, {'type': 'segment', 'endpoint': array([1175.       , 3890.2313846]), 'startpoint': array([1175., 3900.])}, {'type': 'turn', 'turn': -0.4934511584543011}, {'type': 'segment', 'endpoint': array([1105.72054048, 3729.18061479]), 'startpoint': array([1159., 3829.])}, {'type': 'turn', 'tu

In [15]:
sys, connections, elements_ = sqd.sample.get_tls(cutoff=2e11)
f, delta, modes = sys.get_modes()
num_modes=18
(res_fr,kappa,_)=auxfuncs.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

('down',)
('up',)


C:\Users\di82dac\Anaconda3\envs\qcreator\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


Resonance frequencies are, GHz/2pi: [4.52133462 4.52175859 5.82822274 5.94357465 6.23383628 6.35672523
 6.52010911 6.64402013 6.6797905  7.37947516 7.56410607]
Kappas are, MHz/2pi: [2.93866718e-04 2.43155157e-04 1.81923200e-01 2.07586056e-01
 2.21566789e-01 2.56018345e-01 1.80268100e-01 2.77791952e-01
 1.00374634e-01 2.75055002e-02 3.00510816e-02]
Quality factors are: [7692832.07148414 9298093.10784708   16018.36037189   14315.92940673
   14067.62338358   12414.58934844   18084.47836791   11958.62601791
   33274.29567177  134145.44538219  125854.13991798]


In [16]:
f[:num_modes]/(2*np.pi)/1e9, delta[:num_modes]

(array([ 4.52133462,  4.52175859,  5.82822274,  5.94357465,  6.23383628,
         6.35672523,  6.52010911,  6.64402013,  6.6797905 ,  7.37947516,
         7.56410607, 16.25477802, 17.59409619, 17.95061247, 18.42787245,
        18.78509677, 19.11743335, 19.11914644]),
 array([1.84641904e+03, 1.52778891e+03, 1.14305717e+06, 1.30430166e+06,
        1.39214519e+06, 1.60861070e+06, 1.13265788e+06, 1.74541831e+06,
        6.30672425e+05, 1.72822155e+05, 1.88816515e+05, 1.68777657e+05,
        1.31377402e+07, 1.09736291e+07, 1.77137683e+11, 1.51464637e+07,
        6.01166263e+06, 6.02523120e+06]))

In [16]:
sqd.sample.write_to_gds()

Gds file has been writen here:  D:\Documents-cloud\qubits\simulation\QCreator\designs\Single_qubit_design\1Q_test.gds


# Simulations

In [17]:
sys, connections, elements_ = sqd.sample.get_tls(cutoff=2e11)
f, delta, modes = sys.get_modes()

('down',)
('up',)


C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [15]:
num_modes=18
(res_fr,kappa,_)=auxfuncs.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

('down',)
('up',)


C:\Users\di82dac\Anaconda3\envs\qcreator\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


Resonance frequencies are, GHz/2pi: [4.52133462 4.52175859 5.82822274 5.94357465 6.23383628 6.35672523
 6.52010911 6.64402013 6.6797905  7.37947516 7.56410607]
Kappas are, MHz/2pi: [2.93866718e-04 2.43155157e-04 1.81923200e-01 2.07586056e-01
 2.21566789e-01 2.56018345e-01 1.80268100e-01 2.77791952e-01
 1.00374634e-01 2.75055002e-02 3.00510816e-02]
Quality factors are: [7692832.07148414 9298093.10784708   16018.36037189   14315.92940673
   14067.62338358   12414.58934844   18084.47836791   11958.62601791
   33274.29567177  134145.44538219  125854.13991798]


In [18]:
num_modes=18
(res_fr,kappa,_)=sqd.search_for_resonators_qubits(f,delta,0,15)[:num_modes]

Resonance frequencies are, GHz/2pi: [4.92754409 4.92786994 4.92816427 4.92841241 5.82237707 5.93725003
 6.23048763 6.3594493  6.4989762  6.63882184 7.39054578 7.5763216 ]
Kappas are, MHz/2pi: [0.00871181 0.00863901 0.00860897 0.00855075 0.18133009 0.20679175
 0.22132931 0.25493007 0.25516803 0.29312784 0.02772073 0.03031085]
Quality factors are: [282808.26117442 285210.266044   286222.54725799 288185.93872864
  16054.63594337  14355.6261769   14075.15255892  12472.92879454
  12734.69930794  11324.10647405 133303.58801683 124977.06592616]


# Get s21 parameters

In [ ]:
f_ = np.linspace(6.9e9, 7.1e9, 2001)
# s11 = sample.get_s21('p1', 'p1', f_)
s11 = sample.get_s21('pad-left-0', 'pad-right-0', f_)

In [ ]:
import resonator_tools
from resonator_tools.circuit import notch_port, reflection_port

In [ ]:
fitter = notch_port(f_data=f_, z_data_raw=s11)
fitter.autofit()

In [ ]:
fitter.plotall()

In [ ]:
fitter.fitresults

# Estimate qubit-resonator parameters

In [9]:
rfr_ind=2
qfr_ind=0

In [10]:
auxfuncs.get_grounded_qubit_resonator_coupling(par1,sqd.coaxmon1,'coupler2',res_fr[rfr_ind],res_fr[qfr_ind])

{'g': (97.56920699063008, 'MHz/2pi')}

In [11]:
auxfuncs.get_grounded_qubit_resonator_parameters(par1,sqd.coaxmon1,'coupler2',res_fr[rfr_ind],res_fr[qfr_ind],kappa[rfr_ind])

Qubit- resonator detuning: -0.49145585956066373


{'g': (97.56920699063008, 'MHz/2pi'),
 'alpha': (-279.1099326319758, 'MHz/2pi'),
 'chi': (-7.016274947557198, 'MHz/2pi'),
 'T': (16.46560784708201, 'us'),
 'protection ratio': 25.371344627775542}

In [12]:
print("From AWR protection ratio is:", kappa[rfr_ind]/kappa[qfr_ind])

From AWR protection ratio is: 28.397216442594896


# Tests

In [10]:
g5,g6,res= sqd.draw_single_resonator(sqd.sample,sqd.elements,
                            sqd.coupler_start+1500, sqd.central_line_y, sqd.coupler_length,
                             sqd.resonator_core,sqd.resonator_gap,sqd.resonator_ground,
                             sqd.tl_core, sqd.tl_gap, sqd.tl_ground, grounding_width=10,
                             closed_end_meander_length=3000,length_left=400,length_right=400,
                             open_end_legth=800,
                             port_orientation='right', direction_orientation='up')