In [1]:
from Conformal_mapping_of_a_coupler import *
import numpy as np
from sympy import *

In [12]:
result=ConformalMapping([1,1,1,1,1,1,1])

In [13]:
C, L = result.cl_and_Ll()

In [14]:
C

array([[ 1.44094517e-10, -4.77550222e-11, -9.44507381e-12],
       [-4.77550222e-11,  1.43839458e-10, -4.77550222e-11],
       [-9.44507381e-12, -4.77550222e-11,  1.44094517e-10]])

In [15]:
L

array([[5.75515894e-07, 2.28768422e-07, 1.13540969e-07],
       [2.28768422e-07, 6.45032486e-07, 2.28768422e-07],
       [1.13540969e-07, 2.28768422e-07, 5.75515894e-07]])

In [17]:
Z

array([[1365.71501822]])