In [1]:
import sys
sys.path.append('..')
from QCreator.transmission_line_simulator import *

In [2]:
import matplotlib.pyplot as plt
from pylab import rcParams
rcParams['figure.figsize'] = 10, 10

In [3]:
import matplotlib.pyplot as plt

# Setup the circuit

In [17]:
line_qubit_capacitor = Capacitor()
line_ground_capacitor = Capacitor()
line_end = Resistor()

GND = Short()
line = TLCoupler(n=1)

qubit_cap = Capacitor()
qubit_inductor = Inductor()

circuit = TLSystem()

circuit.add_element(qubit_cap, [1,0])
circuit.add_element(qubit_inductor, [1,0])
circuit.add_element(line_qubit_capacitor, [1,2])
circuit.add_element(line_ground_capacitor, [2,0])
circuit.add_element(line, [2,3])
circuit.add_element(line_end, [3,0])
circuit.add_element(GND, [0])

In [27]:
line.l = 10e-3
line.Cl = 146.305e-12
line.Ll = 529.989e-9
line.Rl = 0
line.Gl = 0

line_end.R=50

qubit_cap.C= 80e-15
qubit_inductor.L=20e-9

line_qubit_capacitor.C=50e-15
line_ground_capacitor.C=1e-9

In [28]:
f, delta, modes=circuit.get_modes()

In [29]:
f/2/np.pi/1e9,2*delta/1e6

(array([ 3.12131524,  5.67871479, 11.40359321, 15.43683772, 16.14283832,
        17.01691099, 17.86804166, 18.41182037, 19.03314313]),
 array([ 2.67396251e-04,  2.70351346e+04,  2.77207443e+04,  9.15134065e+03,
         1.07748444e+05,  1.86736305e+04,  1.76941034e+05, -1.18528397e+05,
        -1.27763166e+05]))

In [30]:
f/2/np.pi/1e9,2*delta/1e6

(array([ 3.12131524,  5.67871479, 11.40359321, 15.43683772, 16.14283832,
        17.01691099, 17.86804166, 18.41182037, 19.03314313]),
 array([ 2.67396251e-04,  2.70351346e+04,  2.77207443e+04,  9.15134065e+03,
         1.07748444e+05,  1.86736305e+04,  1.76941034e+05, -1.18528397e+05,
        -1.27763166e+05]))